#!/usr/bin/perl

# Set permissions
`chmod +x cdconf`;
`chmod +x cdconfig.cgi`;


# Add cdconf to adminshell
my $shellf = "../adminshell.html";
my $tmpname = "tmpfile.html";
my $commln = '    <script src="cryptodemo/cdinst.js"></script>';

# open files
open(my $fin, '<:encoding(UTF-8)', $shellf)
    or die "Could not open file '$shellf' $!";
open(my $fout, '>:encoding(UTF-8)', $tmpname)
    or die "Could not open file '$tmpname' $!";

# create new shellf
while(<$fin>) {
    if ($_ =~ /<!-- END LOAD COMMAND PLUGINS -->/) {
	print $fout $commln."\n";
    }
    print $fout $_;
}
close($fin);
close($fout);
`mv -f $tmpname $shellf`;


